### ISSUE TITLE
User-style image zoom levels

### ISSUE THREAD

**Issue by zuben00** [nonta1234/terraining-heightmap-generator#21]
User-style downloads work well. Thank you for adding the feature.

The data is not displayed at the zoom level of the image you are currently downloading.
 I understand that the default dataset in the map box can only show data from zoom levels '13' to '22'. 

Is it possible to download an image with a zoom level of '13'?

User-style image showing a railroad and bridge
![246](https://github.com/nonta1234/terraining-heightmap-generator/assets/166455485/eaaaf895-ba5e-463f-ab72-826f3d32e147)
![245](https://github.com/nonta1234/terraining-heightmap-generator/assets/166455485/04a1dcc7-0d10-4a25-be47-1f53867bc011)

**Comment by nonta1234** [comment]
I am requesting that the Mapbox static images api fit the bounding box of the grid size, and in that case the zoom level will be auto. In order to match the grid range while specifying the zoom level, a completely different method is required.

It won't be possible right away, but I'll look into ways to do it.

**Comment by nonta1234** [comment]
[v1.5.0](https://github.com/nonta1234/terraining-heightmap-generator/releases/tag/v1.5.0) available.
