### ISSUE TITLE
longitude and latitude coordinates of the 4 corners

### ISSUE THREAD

**Issue by Daylen69** [nonta1234/terraining-heightmap-generator#5]
Hi !

For a map size of 57.344 km, what is the zoom level of the downloaded map image ?

Would it be possible to know the longitude and latitude coordinates of the 4 corners of the 'green zone' (playable zone) ?

**Comment by nonta1234** [comment]
> For a map size of 57.344 km, what is the zoom level of the downloaded map image ?

The MapBox API does not specify a zoom level if the grid angle is 0 degrees when capturing still images. Just get the map extent. When acquiring still images using the Mapbox API, the zoom level can only be specified to the second decimal place, so if the grid angle is other than 0 degrees, the zoom level with the least deviation is 

> Would it be possible to know the longitude and latitude coordinates of the 4 corners of the 'green zone' (playable zone) ?

It is possible to obtain the latitude and longitude of the corner of the playable zone.
However, strictly speaking there is a very small discrepancy between the grid and the heightmap. This is by design of Mapbox GL JS and Web Mercator.

Which do you think should be displayed?

**Comment by nonta1234** [comment]
I understood.
But Universal Maps Downloader doesn't take map rotation into account, so I have to think about it.

**Comment by Daylen69** [comment]
I talked about Universal maps downloader just as an example because I used it to obtain a map and I needed the coordinates of the 4 corners of the area (I can't be precise so I have an offset at  every time)

**Comment by benmarten** [comment]
I'd welcome this feature too.

I tried manually calculating the bounding box via:
```
const turf = require('@turf/turf')

const centerPoint = [-111.63, 35.19]
const sideLength = 57.344
const center = turf.point(centerPoint)
const box = turf.bbox(
  turf.buffer(center, sideLength / 2, { units: 'kilometers' })
)

const result = {
  type: 'Feature',
  properties: {},
  geometry: {
    type: 'Polygon',
    coordinates: [
      [
        [box[0], box[1]],
        [box[0], box[3]],
        [box[2], box[3]],
        [box[2], box[1]],
      ],
    ],
  },
}

console.log(JSON.stringify(result, null, 2))
```

Which works, but doesn't seem to give the same coordinates as shown on your tool. Any ideas?

**Comment by benmarten** [comment]
I've digged into the code, and it looks like the 4 values are already calculated when downloading the IMG:
<img width="1224" alt="Screenshot 2024-03-27 at 1 32 56 PM" src="https://github.com/nonta1234/terraining-heightmap-generator/assets/5960238/77ae38f1-c287-421e-b125-4cd100f4b345">

Here, we could probably also add an option to make a separate image query for each tile....

**Comment by benmarten** [comment]
I've hacked a PR, that allows for downloading of 6x6 high-res tile images: https://github.com/nonta1234/terraining-heightmap-generator/pull/10#issue-2211965748

**Comment by nonta1234** [comment]
Hi!

The function to get the extent is as follows.

https://github.com/nonta1234/terraining-heightmap-generator/blob/d09987f25f7f5d952448b1c7d0d5bac32e0da3dd/src/composables/useMapbox.ts#L9-L46

The buffer function may not return a perfect circle, because web Mercator is not conformal. Therefore, after converting to pixel coordinates, use the Pythagorean theorem to calculate the length of the side that is expected to have the least deviation. Also, originally the distance on the map increases towards the poles, but for convenience, the boundaries are acquired so that the latitude and longitude of the center is the center of the extent.

Therefore, if you want to split this extent, we recommend separating on a pixel basis.

**Comment by nonta1234** [comment]
v1.4.0
